server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.lab.masales.cloud:8443/realms/demo-te
          use-cache: true
      public-key:
        location: keycloak.pem
keycloak:
  token:
    exchange:
      endpoint: https://keycloak.lab.masales.cloud:8443/realms/demo-te/protocol/openid-connect/token
      client-id: internal-client
      client-secret: XiQ6AagGgXX6UQHwbUBvPisOhAayEBnI





